export const JWT_AUTH_SUCCESS = 'JWT_AUTH_SUCCESS';
export const JWT_AUTH_REQUEST = 'JWT_AUTH_REQUEST';
export const JWT_AUTH_FAILURE = 'JWT_AUTH_FAILURE';

export const LOGOUT = 'LOGOUT';

export const UPDATE_SALARY_REQUEST = 'UPDATE_SALARY_REQUEST';
export const UPDATE_SALARY_SUCCESS = 'UPDATE_SALARY_SUCCESS';
export const UPDATE_SALARY_FAILURE = 'UPDATE_SALARY_FAILURE';

export const ADD_EXPENSE_REQUEST = 'ADD_EXPENSE_REQUEST';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const ADD_EXPENSE_FAILURE = 'ADD_EXPENSE_FAILURE';
